### ISSUE TITLE
Card detail page design

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/dashboard#4]
After clicking on a specific card on the dashboard, the card detail page is displayed. We need to consider the best way to present additional details about the metric to the user.

Example:
https://bloomington.in.gov/performance/cards/2

**Comment by quarterback** [comment]
![ontime_concept](https://cloud.githubusercontent.com/assets/4461062/19743559/b1df3988-9b97-11e6-8da8-ea882b1d182d.png) 

The existing format is very clumsy and I'm just not sure it makes a ton of sense to present users with raw (out of context) data they won't be able to parse.

This idea presents the relevantly daily % over time, my mockup is set to weekly.
