### ISSUE TITLE
Way to display a group of cards

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/dashboard#5]
Cards can be assigned to a group (indicated with an icon). 
We don't have a way to show all cards belonging to a group (and only those cards). 
This issue needs a design for what the interface should look like.

**Comment by rbdietz** [comment]
When we get to this, groups and icons should probably untangled.

**Comment by rbdietz** [comment]
This should probably be a tagging system.  cards can have multiple tags.

**Comment by rbdietz** [comment]
Groups need to be tags.  Cards can exist in multiple groups.  The card interface should allow placing card into one or more grouping.
